import { Food } from "./app/components/shared/models/food"
import { tag } from "./app/components/shared/models/tags"
export const sample_food:Food[]=[
 {
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'2',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'assets/food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'3',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'assets/food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '7',
    name: 'Spaghetti Carbonara',
    price: 15,
    cookTime: '20-25',
    favorite: true,
    origins: ['italy'],
    stars: 4.6,
    imageUrl: 'assets/Spaghetti Carbonara.jpeg',
    tags: ['Pasta', 'Italian', 'Lunch'],
  },
  {
    id: '8',
    name: 'Sushi Rolls',
    price: 18,
    cookTime: '30-40',
    favorite: true,
    origins: ['japan'],
    stars: 4.8,
    imageUrl: 'assets/Sushi Rolls.jpeg',
    tags: ['Seafood', 'Japanese', 'Dinner'],
  },
  {
    id: '9',
    name: 'Chicken Tikka',
    price: 12,
    cookTime: '30-40',
    favorite: false,
    origins: ['india'],
    stars: 4.3,
    imageUrl: 'assets/Chicken Tikka.jpeg',
    tags: ['Grilled', 'Indian', 'Dinner'],
  },
  {
    id: '10',
    name: 'Greek Salad',
    price: 8,
    cookTime: '10-15',
    favorite: false,
    origins: ['greece'],
    stars: 4.4,
    imageUrl: 'assets/Greek Salad.jpeg',
    tags: ['Salad', 'Greek', 'Lunch'],
  },
  {
    id: '11',
    name: 'Burrito',
    price: 14,
    cookTime: '15-20',
    favorite: true,
    origins: ['mexico'],
    stars: 4.7,
    imageUrl: 'assets/Burrito.jpeg',
    tags: ['Mexican', 'Wrap', 'Lunch'],
  },
  {
    id: '12',
    name: 'Pad Thai',
    price: 13,
    cookTime: '20-30',
    favorite: false,
    origins: ['thailand'],
    stars: 4.5,
    imageUrl: 'assets/pad-thai-6.jpg',
    tags: ['Noodles', 'Thai', 'Dinner'],
  },
  {
    id: '13',
    name: 'Beef Stroganoff',
    price: 16,
    cookTime: '30-40',
    favorite: false,
    origins: ['russia'],
    stars: 4.2,
    imageUrl: 'assets/Beef Stroganoff.jpeg',
    tags: ['Beef', 'Russian', 'Dinner'],
  },
  {
    id: '14',
    name: 'Falafel',
    price: 7,
    cookTime: '15-20',
    favorite: true,
    origins: ['middle east'],
    stars: 4.6,
    imageUrl: 'assets/Falafel.jpeg',
    tags: ['Vegetarian', 'Middle Eastern', 'Snack'],
  },
  {
    id: '15',
    name: 'Apple Pie',
    price: 6,
    cookTime: '45-55',
    favorite: true,
    origins: ['us'],
    stars: 4.7,
    imageUrl: 'assets/Apple Pie.jpeg',
    tags: ['Dessert', 'American'],
  },
  {
    id: '16',
    name: 'Paella',
    price: 22,
    cookTime: '50-60',
    favorite: false,
    origins: ['spain'],
    stars: 4.4,
    imageUrl: 'assets/Paella.jpeg',
    tags: ['Seafood', 'Spanish', 'Dinner'],
  }
]

export const sample_tags: tag[] = [
  { name: 'All', count: 16 },
  { name: 'FastFood', count: 5 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 7 },
  { name: 'SlowFood', count: 3 },
  { name: 'Dinner', count: 7 },
  { name: 'Vegetarian', count: 1 },
  { name: 'Dessert', count: 1 },
  { name: 'Seafood', count: 2 }
]